Vagrant.configure('2') do |config|
    config.vm.provision 'shell', inline: <<-EOF
        type yum > /dev/null 2>1 || exit 0

        cd ~

        sudo yum install -y git vim

        git clone https://github.com/ben-rosio/dotfiles
        ./dotfiles/install.sh
        git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
        vim +PluginInstall +qall
    EOF
end