Vagrant.configure('2') do |config|
    config.vm.provision 'shell', privileged: false, inline: <<-EOF
        type yum > /dev/null 2>&1 || exit 0

        cd ~

        sudo yum install -y git vim

        git clone https://github.com/ben-rosio/dotfiles
        ./dotfiles/install.sh
    EOF
end
