installDotfiles = (ENV['DOTFILES'] == nil || ENV['DOTFILES'].downcase == 'true')

Vagrant.configure('2') do |config|
    config.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']

        aws.keypair_name = 'vagrant'
        override.ssh.private_key_path = '~/.ssh/aws-vagrant'
    end

    if installDotfiles
        config.vm.provision 'shell', privileged: false, inline: <<-EOF
            type yum > /dev/null 2>&1 || exit 0

            cd ~

            sudo yum install -y git vim

            git clone https://github.com/ben-rosio/dotfiles
            ./dotfiles/install.sh
        EOF
    end
end
